# Generated by Django 6.0.1 on 2026-01-23 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(help_text='Name of the unit', max_length=200)),
                ('unit_evidence_id', models.CharField(help_text='Unit evidence ID (e.g., 523.10, 816.08.001)', max_length=50)),
                ('contact_person_name', models.CharField(help_text='Name of the contact person', max_length=200)),
                ('contact_email', models.EmailField(help_text='Contact email address', max_length=254)),
                ('contact_phone', models.CharField(help_text='Contact phone number', max_length=20)),
                ('backup_contact_phone', models.CharField(blank=True, help_text='Optional backup contact phone', max_length=20)),
                ('relevant_information', models.TextField(blank=True, help_text='Any relevant information about the unit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['unit_name'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, help_text='Optional nickname', max_length=100)),
                ('date_of_birth', models.DateField(help_text='Date of birth')),
                ('health_restrictions', models.TextField(blank=True, help_text='Any health restrictions or medical conditions')),
                ('dietary_restrictions', models.TextField(blank=True, help_text='Any dietary restrictions or preferences')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='SkaRe.unit')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
