# Generated by Django 6.0.1 on 2026-01-25 17:16

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_deadline', models.DateTimeField(default=datetime.datetime(2027, 1, 25, 17, 16, 2, 998656, tzinfo=datetime.timezone.utc), help_text='Deadline for creating new Units and Participants')),
            ],
            options={
                'verbose_name': 'Event Settings',
                'verbose_name_plural': 'Event Settings',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_for_editing', models.BooleanField(default=False, help_text='Whether this unit is unlocked for editing after the deadline (set by privileged users only)')),
                ('is_individual', models.BooleanField(default=False, help_text='Whether this unit represents an individual registration')),
                ('unit_name', models.CharField(help_text='Name of the unit', max_length=200)),
                ('unit_evidence_id', models.CharField(help_text='Unit evidence ID (e.g., 523.10, 816.08.001)', max_length=50)),
                ('contact_person_name', models.CharField(help_text='Name of the contact person', max_length=200)),
                ('contact_email', models.EmailField(help_text='Contact email address', max_length=254)),
                ('contact_phone', models.CharField(help_text='Contact phone number', max_length=20)),
                ('backup_contact_phone', models.CharField(blank=True, help_text='Optional backup contact phone', max_length=20)),
                ('relevant_information', models.TextField(blank=True, help_text='Any relevant information about the unit')),
                ('expected_arrival', models.DateTimeField(blank=True, help_text='Expected date and time of arrival', null=True)),
                ('expected_departure', models.DateTimeField(blank=True, help_text='Expected date and time of departure', null=True)),
                ('home_town', models.CharField(blank=True, help_text='Home town of the unit', max_length=200)),
                ('boats_p550', models.PositiveIntegerField(default=0, help_text='Estimated number of P550 boats')),
                ('boats_sail', models.PositiveIntegerField(default=0, help_text='Estimated number of other sail-boats')),
                ('boats_paddle', models.PositiveIntegerField(default=0, help_text='Estimated number of paddle-powered boats')),
                ('boats_motor', models.PositiveIntegerField(default=0, help_text='Estimated number of motor-powered boats')),
                ('accommodation_expectations', models.TextField(blank=True, help_text='Accommodation expectations')),
                ('estimated_accommodation_area', models.CharField(blank=True, help_text='Estimated needed area for accommodation', max_length=100)),
                ('wishes_notes', models.TextField(blank=True, help_text='Wishes, notes, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this unit', on_delete=django.db.models.deletion.CASCADE, related_name='units', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['unit_name'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, help_text='Optional nickname', max_length=100)),
                ('date_of_birth', models.DateField(help_text='Date of birth')),
                ('category', models.CharField(choices=[('ADULT', 'Adult'), ('ROVER', 'Rover'), ('SCOUT', 'Scout'), ('CUB', 'Cub')], default='SCOUT', help_text='Scout category', max_length=20)),
                ('health_restrictions', models.TextField(blank=True, help_text='Any health restrictions or medical conditions')),
                ('dietary_restrictions', models.TextField(blank=True, help_text='Any dietary restrictions or preferences')),
                ('relevant_information', models.TextField(blank=True, help_text='Any relevant information about the participant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='SkaRe.unit')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
