# Generated by Django 6.0.1 on 2026-01-26 01:36

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_deadline', models.DateTimeField(default=datetime.datetime(2027, 1, 26, 1, 36, 56, 117229, tzinfo=datetime.timezone.utc), help_text='Deadline for creating new Units and Participants')),
            ],
            options={
                'verbose_name': 'Event Settings',
                'verbose_name_plural': 'Event Settings',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, help_text='Optional nickname', max_length=100)),
                ('date_of_birth', models.DateField(help_text='Date of birth')),
                ('category', models.CharField(choices=[('ADULT', 'Adult'), ('ROVER', 'Rover'), ('SCOUT', 'Scout'), ('CUB', 'Cub')], default='SCOUT', help_text='Scout category', max_length=20)),
                ('health_restrictions', models.TextField(blank=True, help_text='Any health restrictions or medical conditions')),
                ('dietary_restrictions', models.TextField(blank=True, help_text='Any dietary restrictions or preferences')),
                ('relevant_information', models.TextField(blank=True, help_text='Any relevant information about the person')),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unlocked_for_editing', models.BooleanField(default=False, help_text='Whether this unit is unlocked for editing after the deadline (set by privileged users only)')),
                ('scout_unit_name', models.CharField(blank=True, help_text='Name of the scout unit', max_length=200)),
                ('scout_unit_evidence_id', models.CharField(blank=True, help_text='Unit evidence ID (e.g., 523.10, 816.08.001)', max_length=50)),
                ('contact_email', models.EmailField(help_text='Contact email address', max_length=254)),
                ('contact_phone', models.CharField(help_text='Contact phone number', max_length=20)),
                ('expected_arrival', models.DateTimeField(blank=True, help_text='Expected date and time of arrival', null=True)),
                ('expected_departure', models.DateTimeField(blank=True, help_text='Expected date and time of departure', null=True)),
                ('home_town', models.CharField(blank=True, help_text='Home town of the unit', max_length=200)),
                ('created_by', models.ForeignKey(help_text='User who created this entry', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person_name', models.CharField(help_text='Name of the contact person', max_length=200)),
                ('backup_contact_phone', models.CharField(blank=True, help_text='Optional backup contact phone', max_length=20)),
                ('boats_p550', models.PositiveIntegerField(default=0, help_text='Estimated number of P550 boats')),
                ('boats_sail', models.PositiveIntegerField(default=0, help_text='Estimated number of other sail-boats')),
                ('boats_paddle', models.PositiveIntegerField(default=0, help_text='Estimated number of paddle-powered boats')),
                ('boats_motor', models.PositiveIntegerField(default=0, help_text='Estimated number of motor-powered boats')),
                ('accommodation_expectations', models.TextField(blank=True, help_text='Accommodation expectations (small tents, large tent, caravan, ...)')),
                ('estimated_accommodation_area', models.CharField(blank=True, help_text='Estimated needed area for accommodation', max_length=100)),
                ('entity', models.OneToOneField(help_text='The registration entity associated with this unit', on_delete=django.db.models.deletion.CASCADE, related_name='unit_profile', to='SkaRe.entity')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualParticipant',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SkaRe.person')),
                ('entity', models.OneToOneField(help_text='The registration entity associated with this individual participant', on_delete=django.db.models.deletion.CASCADE, related_name='individual_participant_profile', to='SkaRe.entity')),
            ],
            bases=('SkaRe.person',),
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SkaRe.person')),
                ('division', models.CharField(choices=[('MANAGEMENT', 'Management'), ('RACING', 'Racing'), ('RESCUE', 'Rescue'), ('CRISIS', 'Crisis'), ('INFORMATION', 'Information'), ('MATERIAL', 'Material'), ('FOOD', 'Food'), ('PROGRAM', 'Program'), ('OTHERS', 'Others')], default='OTHERS', help_text='Division the organizer belongs to', max_length=20)),
                ('transport', models.CharField(choices=[('PUBLIC', 'Public Transport'), ('CAR', 'Car'), ('CAR_WITH_TRAILER', 'Car with Trailer')], default='PUBLIC', help_text='Transport method to the event', max_length=20)),
                ('need_lift', models.BooleanField(default=False, help_text='Whether the organizer needs a lift from the nearest transport hub')),
                ('want_travel_order', models.BooleanField(default=False, help_text='Whether the organizer wants a travel order for reimbursement')),
                ('accommodation', models.CharField(choices=[('WITH_UNIT', 'With Unit'), ('OWN_TENT', 'Own Tent'), ('CARAVAN', 'Caravan'), ('NEED_TENT', 'Need Tent'), ('INSIDE_BUILDING', 'Inside Building')], default='OWN_TENT', help_text='Accommodation preference of the organizer', max_length=20)),
                ('codex_agreement', models.BooleanField(default=False, help_text='Whether the organizer agrees to follow the event codex')),
                ('entity', models.OneToOneField(help_text='The registration entity associated with this organizer', on_delete=django.db.models.deletion.CASCADE, related_name='organizer_profile', to='SkaRe.entity')),
            ],
            bases=('SkaRe.person',),
        ),
        migrations.CreateModel(
            name='RegularParticipant',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SkaRe.person')),
                ('unit', models.ForeignKey(help_text='The unit this participant belongs to', on_delete=django.db.models.deletion.RESTRICT, related_name='regular_participants', to='SkaRe.unit')),
            ],
            bases=('SkaRe.person',),
        ),
    ]
