# Generated by Django 6.0.1 on 2026-01-26 01:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkaRe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='accepted',
            field=models.BooleanField(default=False, help_text='Whether the registration has been accepted (set by privileged users only)'),
        ),
        migrations.AddField(
            model_name='entity',
            name='paid',
            field=models.BooleanField(default=False, help_text='Whether the registration fee has been paid (set by privileged users only)'),
        ),
        migrations.AlterField(
            model_name='eventsettings',
            name='registration_deadline',
            field=models.DateTimeField(default=datetime.datetime(2027, 1, 26, 1, 46, 20, 130251, tzinfo=datetime.timezone.utc), help_text='Deadline for creating new Units and Participants'),
        ),
    ]
