# Generated by Django 6.0.1 on 2026-01-23 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkaRe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='category',
            field=models.CharField(choices=[('ADULT', 'Adult'), ('ROVER', 'Rover'), ('SCOUT', 'Scout'), ('CUB', 'Cub')], default='SCOUT', help_text='Scout category', max_length=20),
        ),
        migrations.AddField(
            model_name='participant',
            name='relevant_information',
            field=models.TextField(blank=True, help_text='Any relevant information about the participant'),
        ),
    ]
