# Generated by Django 6.0.1 on 2026-01-26 00:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkaRe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='scout_unit',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='scout_unit',
        ),
        migrations.AddField(
            model_name='entity',
            name='scout_unit_evidence_id',
            field=models.CharField(blank=True, help_text='Unit evidence ID (e.g., 523.10, 816.08.001)', max_length=50),
        ),
        migrations.AddField(
            model_name='entity',
            name='scout_unit_name',
            field=models.CharField(blank=True, help_text='Name of the scout unit', max_length=200),
        ),
        migrations.AddField(
            model_name='unit',
            name='scout_unit_evidence_id',
            field=models.CharField(blank=True, help_text='Unit evidence ID (e.g., 523.10, 816.08.001)', max_length=50),
        ),
        migrations.AddField(
            model_name='unit',
            name='scout_unit_name',
            field=models.CharField(blank=True, help_text='Name of the scout unit', max_length=200),
        ),
        migrations.AlterField(
            model_name='eventsettings',
            name='registration_deadline',
            field=models.DateTimeField(default=datetime.datetime(2027, 1, 26, 0, 37, 56, 62105, tzinfo=datetime.timezone.utc), help_text='Deadline for creating new Units and Participants'),
        ),
        migrations.DeleteModel(
            name='ScoutUnit',
        ),
    ]
