# Generated by Django 6.0.1 on 2026-01-27 21:04

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkaRe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='contact_email',
            field=models.EmailField(help_text='Contact email address', max_length=254, verbose_name='Contact email'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='contact_phone',
            field=models.CharField(help_text='Contact phone number', max_length=20, verbose_name='Contact phone'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this entry', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='expected_arrival',
            field=models.DateTimeField(blank=True, help_text='Expected date and time of arrival', null=True, verbose_name='Expected arrival'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='expected_departure',
            field=models.DateTimeField(blank=True, help_text='Expected date and time of departure', null=True, verbose_name='Expected departure'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='home_town',
            field=models.CharField(blank=True, help_text='Home town of the unit', max_length=200, verbose_name='Home town'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='scout_unit_evidence_id',
            field=models.CharField(blank=True, help_text='Unit evidence ID (e.g., 523.10, 816.08.001)', max_length=50, verbose_name='Evidence ID'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='scout_unit_name',
            field=models.CharField(blank=True, help_text='Name of the scout unit', max_length=200, verbose_name='Scout unit name'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='unlocked_for_editing',
            field=models.BooleanField(default=False, help_text='Whether this unit is unlocked for editing after the deadline (set by privileged users only)', verbose_name='Unlocked for editing'),
        ),
        migrations.AlterField(
            model_name='eventsettings',
            name='registration_deadline',
            field=models.DateTimeField(default=datetime.datetime(2027, 1, 27, 21, 4, 4, 450572, tzinfo=datetime.timezone.utc), help_text='Deadline for creating new Units and Participants'),
        ),
        migrations.AlterField(
            model_name='individualparticipant',
            name='entity',
            field=models.OneToOneField(help_text='The registration entity associated with this individual participant', on_delete=django.db.models.deletion.CASCADE, related_name='individual_participant_profile', to='SkaRe.entity', verbose_name='Entity'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='accommodation',
            field=models.CharField(choices=[('WITH_UNIT', 'With Unit'), ('OWN_TENT', 'Own Tent'), ('CARAVAN', 'Caravan'), ('NEED_TENT', 'Need Tent'), ('INSIDE_BUILDING', 'Inside Building')], default='OWN_TENT', help_text='Accommodation preference of the organizer', max_length=20, verbose_name='Accommodation'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='codex_agreement',
            field=models.BooleanField(default=False, help_text='Whether the organizer agrees to follow the event codex', verbose_name='Codex agreement'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='division',
            field=models.CharField(choices=[('MANAGEMENT', 'Management'), ('RACING', 'Racing'), ('RESCUE', 'Rescue'), ('CRISIS', 'Crisis'), ('INFORMATION', 'Information'), ('MATERIAL', 'Material'), ('FOOD', 'Food'), ('PROGRAM', 'Program'), ('OTHERS', 'Others')], default='OTHERS', help_text='Division the organizer belongs to', max_length=20, verbose_name='Division'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='entity',
            field=models.OneToOneField(help_text='The registration entity associated with this organizer', on_delete=django.db.models.deletion.CASCADE, related_name='organizer_profile', to='SkaRe.entity', verbose_name='Entity'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='need_lift',
            field=models.BooleanField(default=False, help_text='Whether the organizer needs a lift from the nearest transport hub', verbose_name='Need lift'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='transport',
            field=models.CharField(choices=[('PUBLIC', 'Public Transport'), ('CAR', 'Car'), ('CAR_WITH_TRAILER', 'Car with Trailer')], default='PUBLIC', help_text='Transport method to the event', max_length=20, verbose_name='Transport'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='want_travel_order',
            field=models.BooleanField(default=False, help_text='Whether the organizer wants a travel order for reimbursement', verbose_name='Want travel order'),
        ),
        migrations.AlterField(
            model_name='person',
            name='category',
            field=models.CharField(blank=True, choices=[('ADULT', 'Adult'), ('ROVER', 'Rover'), ('SCOUT', 'Scout'), ('CUB', 'Cub')], default='SCOUT', help_text='Scout category', max_length=20, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(help_text='Date of birth', verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='person',
            name='dietary_restrictions',
            field=models.TextField(blank=True, help_text='Any dietary restrictions or preferences', verbose_name='Dietary restrictions'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='health_restrictions',
            field=models.TextField(blank=True, help_text='Any health restrictions or medical conditions', verbose_name='Health restrictions'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='nickname',
            field=models.CharField(blank=True, help_text='Optional nickname', max_length=100, verbose_name='Nickname'),
        ),
        migrations.AlterField(
            model_name='person',
            name='relevant_information',
            field=models.TextField(blank=True, help_text='Any relevant information about the person', verbose_name='Relevant information'),
        ),
        migrations.AlterField(
            model_name='regularparticipant',
            name='unit',
            field=models.ForeignKey(help_text='The unit this participant belongs to', on_delete=django.db.models.deletion.RESTRICT, related_name='regular_participants', to='SkaRe.unit', verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='accommodation_expectations',
            field=models.TextField(blank=True, help_text='Accommodation expectations (small tents, large tent, caravan, ...)', verbose_name='Accommodation expectations'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='backup_contact_phone',
            field=models.CharField(blank=True, help_text='Optional backup contact phone', max_length=20, verbose_name='Backup contact phone'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='boats_motor',
            field=models.PositiveIntegerField(default=0, help_text='Estimated number of motor-powered boats', verbose_name='Motor boats'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='boats_p550',
            field=models.PositiveIntegerField(default=0, help_text='Estimated number of P550 boats', verbose_name='P550 boats'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='boats_paddle',
            field=models.PositiveIntegerField(default=0, help_text='Estimated number of paddle-powered boats', verbose_name='Paddle boats'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='boats_sail',
            field=models.PositiveIntegerField(default=0, help_text='Estimated number of other sail-boats', verbose_name='Sail boats'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='contact_person_name',
            field=models.CharField(help_text='Name of the contact person', max_length=200, verbose_name='Contact person name'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='entity',
            field=models.OneToOneField(help_text='The registration entity associated with this unit', on_delete=django.db.models.deletion.CASCADE, related_name='unit_profile', to='SkaRe.entity', verbose_name='Entity'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='estimated_accommodation_area',
            field=models.CharField(blank=True, help_text='Estimated needed area for accommodation', max_length=100, verbose_name='Estimated accommodation area'),
        ),
    ]
