# Generated by Django 6.0.1 on 2026-01-25 23:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkaRe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='The unit this participant belongs to', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='participants', to='SkaRe.unit'),
        ),
        migrations.AlterField(
            model_name='eventsettings',
            name='registration_deadline',
            field=models.DateTimeField(default=datetime.datetime(2027, 1, 25, 23, 21, 30, 533668, tzinfo=datetime.timezone.utc), help_text='Deadline for creating new Units and Participants'),
        ),
    ]
