# Generated by Django 6.0.1 on 2026-01-23 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SkaRe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='phone',
        ),
    ]
