# Generated by Django 6.0.1 on 2026-01-27 21:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkaRe', '0002_alter_entity_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsettings',
            name='registration_deadline',
            field=models.DateTimeField(default=datetime.datetime(2027, 1, 27, 21, 4, 30, 289483, tzinfo=datetime.timezone.utc), help_text='Deadline for creating new Units and Participants'),
        ),
    ]
