# Generated by Django 6.0.1 on 2026-01-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkaRe', '0002_participant_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='accommodation_expectations',
            field=models.TextField(blank=True, help_text='Accommodation expectations'),
        ),
        migrations.AddField(
            model_name='unit',
            name='boats_motor',
            field=models.PositiveIntegerField(default=0, help_text='Estimated number of motor-powered boats'),
        ),
        migrations.AddField(
            model_name='unit',
            name='boats_p550',
            field=models.PositiveIntegerField(default=0, help_text='Estimated number of P550 boats'),
        ),
        migrations.AddField(
            model_name='unit',
            name='boats_paddle',
            field=models.PositiveIntegerField(default=0, help_text='Estimated number of paddle-powered boats'),
        ),
        migrations.AddField(
            model_name='unit',
            name='boats_sail',
            field=models.PositiveIntegerField(default=0, help_text='Estimated number of other sail-boats'),
        ),
        migrations.AddField(
            model_name='unit',
            name='estimated_accommodation_area',
            field=models.CharField(blank=True, help_text='Estimated needed area for accommodation', max_length=100),
        ),
        migrations.AddField(
            model_name='unit',
            name='expected_arrival',
            field=models.DateTimeField(blank=True, help_text='Expected date and time of arrival', null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='expected_departure',
            field=models.DateTimeField(blank=True, help_text='Expected date and time of departure', null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='home_town',
            field=models.CharField(blank=True, help_text='Home town of the unit', max_length=200),
        ),
        migrations.AddField(
            model_name='unit',
            name='wishes_notes',
            field=models.TextField(blank=True, help_text='Wishes, notes, etc.'),
        ),
    ]
