# Generated by Django 6.0.1 on 2026-01-26 00:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkaRe', '0002_remove_entity_scout_unit_remove_unit_scout_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='scout_unit_evidence_id',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='scout_unit_name',
        ),
        migrations.AlterField(
            model_name='eventsettings',
            name='registration_deadline',
            field=models.DateTimeField(default=datetime.datetime(2027, 1, 26, 0, 44, 51, 287988, tzinfo=datetime.timezone.utc), help_text='Deadline for creating new Units and Participants'),
        ),
    ]
