# Generated by Django 6.0.1 on 2026-01-27 21:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkaRe', '0003_alter_eventsettings_registration_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsettings',
            name='registration_deadline',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 1, 23, 59, 59, tzinfo=datetime.timezone.utc), help_text='Deadline for creating new Units and Participants'),
        ),
        migrations.AlterField(
            model_name='person',
            name='category',
            field=models.CharField(blank=True, choices=[('ADULT', 'Adult'), ('ROVER', 'Rover'), ('SCOUT', 'Scout'), ('CUB', 'Cub')], default=None, help_text='Scout category', max_length=20, null=True, verbose_name='Category'),
        ),
    ]
