# Generated by Django 6.0.1 on 2026-01-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkaRe', '0003_unit_accommodation_expectations_unit_boats_motor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='is_individual',
            field=models.BooleanField(default=False, help_text='Whether this unit represents an individual registration'),
        ),
    ]
