# Generated by Django 6.0.1 on 2026-01-25 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkaRe', '0004_unit_is_individual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_deadline', models.DateTimeField(help_text='Deadline for creating new Units and Participants')),
                ('event_name', models.CharField(default='Event', help_text='Name of the event', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event Settings',
                'verbose_name_plural': 'Event Settings',
            },
        ),
        migrations.AddField(
            model_name='unit',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this unit', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unit',
            name='unlocked_for_editing',
            field=models.BooleanField(default=False, help_text='Whether this unit is unlocked for editing after the deadline (set by privileged users only)'),
        ),
    ]
