# Generated by Django 6.0.1 on 2026-02-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkaRe', '0004_alter_eventsettings_registration_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualparticipant',
            name='accommodation_expectations',
            field=models.TextField(blank=True, help_text='Accommodation expectations (small tents, large tent, caravan, ...)', verbose_name='Accommodation expectations'),
        ),
        migrations.AddField(
            model_name='individualparticipant',
            name='boats_motor',
            field=models.PositiveIntegerField(default=0, help_text='Estimated number of motor-powered boats', verbose_name='Motor boats'),
        ),
        migrations.AddField(
            model_name='individualparticipant',
            name='boats_p550',
            field=models.PositiveIntegerField(default=0, help_text='Estimated number of P550 boats', verbose_name='P550 boats'),
        ),
        migrations.AddField(
            model_name='individualparticipant',
            name='boats_paddle',
            field=models.PositiveIntegerField(default=0, help_text='Estimated number of paddle-powered boats', verbose_name='Paddle boats'),
        ),
        migrations.AddField(
            model_name='individualparticipant',
            name='boats_sail',
            field=models.PositiveIntegerField(default=0, help_text='Estimated number of other sail-boats', verbose_name='Sail boats'),
        ),
        migrations.AddField(
            model_name='individualparticipant',
            name='estimated_accommodation_area',
            field=models.CharField(blank=True, help_text='Estimated needed area for accommodation', max_length=100, verbose_name='Estimated accommodation area'),
        ),
    ]
