# Generated by Django 6.0.1 on 2026-02-01 15:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkaRe', '0004_alter_eventsettings_registration_deadline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='editors',
            field=models.ManyToManyField(blank=True, help_text='Users who can edit this entry (in addition to the creator)', related_name='editable_entities', to=settings.AUTH_USER_MODEL, verbose_name='Editors'),
        ),
    ]
