# Generated by Django 6.0.1 on 2026-01-25 14:20

from django.db import migrations


def assign_units_to_first_superuser(apps, schema_editor):
    """
    Assign all existing units (with null created_by) to the first superuser.
    If no superuser exists, create a placeholder user.
    """
    Unit = apps.get_model('SkaRe', 'Unit')
    User = apps.get_model('auth', 'User')
    
    # Get units with null created_by
    units_without_owner = Unit.objects.filter(created_by__isnull=True)
    
    if units_without_owner.exists():
        # Try to get the first superuser
        superuser = User.objects.filter(is_superuser=True).first()
        
        if not superuser:
            # If no superuser exists, get the first user or create a placeholder
            superuser = User.objects.first()
            
            if not superuser:
                # Create a placeholder admin user
                superuser = User.objects.create_user(
                    username='admin',
                    email='admin@example.com',
                    is_staff=True,
                    is_superuser=True
                )
                superuser.set_password('admin')  # Should be changed immediately
                superuser.save()
        
        # Assign all units without owner to the superuser
        units_without_owner.update(created_by=superuser)


def reverse_assignment(apps, schema_editor):
    """
    Reverse the assignment by setting created_by back to null.
    """
    Unit = apps.get_model('SkaRe', 'Unit')
    Unit.objects.all().update(created_by=None)


class Migration(migrations.Migration):

    dependencies = [
        ('SkaRe', '0005_add_security_features'),
    ]

    operations = [
        migrations.RunPython(assign_units_to_first_superuser, reverse_assignment),
    ]
