# Generated by Django 6.0.1 on 2026-02-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkaRe', '0005_individualparticipant_accommodation_expectations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualparticipant',
            name='scarf_count',
            field=models.PositiveBigIntegerField(default=0, help_text='Number of scarves', verbose_name='Scarf count'),
        ),
        migrations.AddField(
            model_name='unit',
            name='scarf_count',
            field=models.PositiveBigIntegerField(default=0, help_text='Number of scarves', verbose_name='Scarf count'),
        ),
    ]
