# Generated by Django 6.0.1 on 2026-02-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkaRe', '0006_individualparticipant_scarf_count_unit_scarf_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualparticipant',
            name='hat_count',
            field=models.PositiveBigIntegerField(default=0, help_text='Number of hats', verbose_name='Hat count'),
        ),
        migrations.AddField(
            model_name='unit',
            name='hat_count',
            field=models.PositiveBigIntegerField(default=0, help_text='Number of hats', verbose_name='Hat count'),
        ),
    ]
