# Generated by Django 6.0.1 on 2026-02-06 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SkaRe', '0005_add_editors_to_entity'),
        ('SkaRe', '0007_individualparticipant_hat_count_unit_hat_count'),
    ]

    operations = [
    ]
