# Generated by Django 6.0.1 on 2026-02-10 19:18

import SkaRe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkaRe', '0009_backfill_category_from_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='wants_hat',
            field=models.BooleanField(default=True, help_text='Whether the organizer wants a hat', verbose_name='Wants hat'),
        ),
        migrations.AddField(
            model_name='organizer',
            name='wants_scarf',
            field=models.BooleanField(default=True, help_text='Whether the organizer wants a scarf', verbose_name='Wants scarf'),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(help_text='Date of birth', validators=[SkaRe.models.validate_date_of_birth], verbose_name='Date of birth'),
        ),
    ]
