# Generated by Django 6.0.1 on 2026-02-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkaRe', '0010_organizer_wants_hat_organizer_wants_scarf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='confirmed',
            field=models.BooleanField(default=False, help_text='Whether this entity has been confirmed', verbose_name='Confirmed'),
        ),
        migrations.AddField(
            model_name='entity',
            name='paid',
            field=models.BooleanField(default=False, help_text='Whether payment has been received for this entity', verbose_name='Paid'),
        ),
    ]
