# Generated by Django 6.0.1 on 2026-02-16 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkaRe', '0011_entity_confirmed_entity_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsettings',
            name='editing_deadline',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 1, 23, 59, 59, tzinfo=datetime.timezone.utc), help_text='Deadline for editing Units and Participants'),
        ),
    ]
