# Generated by Django 6.0.1 on 2026-03-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkaRe', '0012_eventsettings_editing_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoatClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('category', models.CharField(choices=[('SAIL', 'Sail'), ('OTHER', 'Other')], max_length=10, verbose_name='Category')),
                ('is_other', models.BooleanField(default=False, help_text="Marks the catch-all 'Other' entry for this category. Convention only — no DB constraint.", verbose_name='Is other')),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls display order in dropdowns.', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Boat class',
                'verbose_name_plural': 'Boat classes',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SailRegistryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sail_number', models.CharField(max_length=50, unique=True, verbose_name='Sail number')),
                ('boat_name', models.CharField(blank=True, max_length=200, verbose_name='Boat name')),
                ('class_name', models.CharField(blank=True, max_length=100, verbose_name='Class name')),
                ('subtype', models.CharField(blank=True, help_text='Prefilled into class_supplement on the boat form.', max_length=200, verbose_name='Subtype')),
                ('sail_area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Sail area')),
                ('harbor_number', models.CharField(blank=True, max_length=100, verbose_name='Harbor number')),
                ('harbor_name', models.CharField(blank=True, max_length=200, verbose_name='Harbor name')),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='Contact person')),
            ],
            options={
                'verbose_name': 'Sail registry entry',
                'verbose_name_plural': 'Sail registry entries',
            },
        ),
    ]
