# Generated by Django 6.0.1 on 2026-03-23 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkaRe', '0013_boatclass_sailregistryentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_supplement', models.CharField(blank=True, max_length=200, verbose_name='Class supplement')),
                ('sail_number', models.CharField(blank=True, max_length=50, verbose_name='Sail number')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('sail_area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Sail area')),
                ('harbor_number', models.CharField(blank=True, max_length=100, verbose_name='Harbor number')),
                ('harbor_name', models.CharField(blank=True, max_length=200, verbose_name='Harbor name')),
                ('contact_person', models.CharField(max_length=200, verbose_name='Contact person')),
                ('contact_phone', models.CharField(max_length=50, verbose_name='Contact phone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boat_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SkaRe.boatclass', verbose_name='Boat class')),
                ('created_by', models.ForeignKey(help_text='Deleting the user also deletes their boats — consistent with Entity.created_by.', on_delete=django.db.models.deletion.CASCADE, related_name='boats', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Boat',
                'verbose_name_plural': 'Boats',
            },
        ),
    ]
