# Generated by Django 6.0.1 on 2026-03-24 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SkaRe', '0016_boatclass_initial_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SailRegistryEntry',
        ),
    ]
