# Generated by Django 6.0.1 on 2026-03-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkaRe', '0017_remove_sailregistryentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='engine_power_hp',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='hull_color',
            field=models.CharField(blank=True, choices=[('bila', 'Bílá'), ('cerna', 'Černá'), ('cervena', 'Červená'), ('modra', 'Modrá'), ('zelena', 'Zelená'), ('zluta', 'Žlutá'), ('oranzova', 'Oranžová'), ('seda', 'Šedá'), ('hneda', 'Hnědá'), ('jina', 'Jiná')], max_length=20),
        ),
        migrations.AddField(
            model_name='boat',
            name='sail_color',
            field=models.CharField(blank=True, choices=[('bila', 'Bílá'), ('cerna', 'Černá'), ('cervena', 'Červená'), ('modra', 'Modrá'), ('zelena', 'Zelená'), ('zluta', 'Žlutá'), ('oranzova', 'Oranžová'), ('seda', 'Šedá'), ('hneda', 'Hnědá'), ('jina', 'Jiná')], max_length=20),
        ),
        migrations.AddField(
            model_name='boat',
            name='vessel_registry_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
