# Generated by Django 6.0.1 on 2026-03-25 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkaRe', '0018_boat_phase_1_1_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualparticipant',
            name='small_hat_count',
            field=models.PositiveBigIntegerField(default=0, help_text='Number of small hats (S/M)', verbose_name='Hat count (S/M)'),
        ),
        migrations.AddField(
            model_name='unit',
            name='small_hat_count',
            field=models.PositiveBigIntegerField(default=0, help_text='Number of small hats (S/M)', verbose_name='Hat count (S/M)'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='boat_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SkaRe.boatclass', verbose_name='boat class'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='class_supplement',
            field=models.CharField(blank=True, max_length=200, verbose_name='class supplement'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='contact_person',
            field=models.CharField(max_length=200, verbose_name='contact person'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='contact_phone',
            field=models.CharField(max_length=50, verbose_name='contact phone'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='engine_power_hp',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='engine power (hp)'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='harbor_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='harbor name'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='harbor_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='harbor number'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='hull_color',
            field=models.CharField(blank=True, choices=[('bila', 'White'), ('cerna', 'Black'), ('cervena', 'Red'), ('modra', 'Blue'), ('zelena', 'Green'), ('zluta', 'Yellow'), ('oranzova', 'Orange'), ('seda', 'Gray'), ('hneda', 'Brown'), ('jina', 'Other')], max_length=20, verbose_name='hull color'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='sail_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='sail area'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='sail_color',
            field=models.CharField(blank=True, choices=[('bila', 'White'), ('cerna', 'Black'), ('cervena', 'Red'), ('modra', 'Blue'), ('zelena', 'Green'), ('zluta', 'Yellow'), ('oranzova', 'Orange'), ('seda', 'Gray'), ('hneda', 'Brown'), ('jina', 'Other')], max_length=20, verbose_name='sail color'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='sail_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='sail number'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='vessel_registry_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='vessel registry number'),
        ),
        migrations.AlterField(
            model_name='individualparticipant',
            name='hat_count',
            field=models.PositiveBigIntegerField(default=0, help_text='Number of large hats (L/XL)', verbose_name='Hat count (L/XL)'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='hat_count',
            field=models.PositiveBigIntegerField(default=0, help_text='Number of large hats (L/XL)', verbose_name='Hat count (L/XL)'),
        ),
    ]
