# Generated by Django 6.0.3 on 2026-03-25 22:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkaRe', '0019_person_visible_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='visible_to',
            field=models.ManyToManyField(blank=True, help_text='Users who can see and select this boat when registering a crew', related_name='borrowed_boats', to=settings.AUTH_USER_MODEL, verbose_name='visible to'),
        ),
        migrations.AddField(
            model_name='boat',
            name='willing_to_lend',
            field=models.BooleanField(default=False, help_text='Check if you are willing to lend this boat for the race', verbose_name='willing to lend'),
        ),
    ]
