# Generated by Django 6.0.3 on 2026-03-25 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkaRe', '0020_boat_lending_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='visible_to',
            field=models.ManyToManyField(blank=True, help_text='Users who can see this person when registering a crew', related_name='borrowed_persons', to=settings.AUTH_USER_MODEL, verbose_name='visible to'),
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Q', 'Q – Žabičky a vlčata'), ('S', 'S – Skautky a skauti'), ('R', 'R – Rangers a roveři'), ('D', 'D – Dospělí'), ('SN', 'SN – Skautští námořníci'), ('DN', 'DN – Dospělí námořníci'), ('OZ', 'OŽ – Open Žáci'), ('OD', 'OD – Open Dospělí'), ('MS', 'MS – Modrá stuha')], max_length=3, verbose_name='category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SkaRe.boat', verbose_name='boat')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'crew',
                'verbose_name_plural': 'crews',
                'unique_together': {('boat', 'category')},
            },
        ),
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('helmsman', 'helmsman'), ('crew', 'crew member')], max_length=10, verbose_name='role')),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='SkaRe.crew', verbose_name='crew')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SkaRe.person', verbose_name='participant')),
            ],
            options={
                'verbose_name': 'crew member',
                'verbose_name_plural': 'crew members',
            },
        ),
    ]
