# Generated by Django 6.0.1 on 2026-03-26 13:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkaRe', '0021_crew_crewmember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='crewmember',
            name='role',
            field=models.CharField(choices=[('helmsman', 'Kormidelník'), ('crew', 'Člen posádky')], max_length=10, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='person',
            name='visible_to',
            field=models.ManyToManyField(blank=True, help_text='Users who can see this person when registering a crew', related_name='borrowed_persons', to=settings.AUTH_USER_MODEL, verbose_name='Visible to'),
        ),
    ]
