# Generated by Django 6.0.1 on 2026-03-26 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SkaRe', '0019_hat_size_split'),
        ('SkaRe', '0022_review_fixes'),
    ]

    operations = [
    ]
