# Generated by Django 6.0.1 on 2026-03-26 22:07

from django.db import migrations, models


def copy_dietary_data(apps, schema_editor):
    Person = apps.get_model('SkaRe', 'Person')
    for person in Person.objects.exclude(dietary_restrictions=''):
        person.diet_other = person.dietary_restrictions
        person.save()


class Migration(migrations.Migration):

    dependencies = [
        ('SkaRe', '0024_race_management_group'),
    ]

    operations = [
        # All AddField operations first
        migrations.AddField(
            model_name='person',
            name='diet_gluten_free',
            field=models.BooleanField(default=False, verbose_name='Gluten-free'),
        ),
        migrations.AddField(
            model_name='person',
            name='diet_lactose_free',
            field=models.BooleanField(default=False, verbose_name='Lactose/dairy-free'),
        ),
        migrations.AddField(
            model_name='person',
            name='diet_no_eggs',
            field=models.BooleanField(default=False, verbose_name='No eggs'),
        ),
        migrations.AddField(
            model_name='person',
            name='diet_no_fish',
            field=models.BooleanField(default=False, verbose_name='No fish'),
        ),
        migrations.AddField(
            model_name='person',
            name='diet_no_fruits',
            field=models.BooleanField(default=False, verbose_name='No fruits'),
        ),
        migrations.AddField(
            model_name='person',
            name='diet_no_peanuts',
            field=models.BooleanField(default=False, verbose_name='No peanuts'),
        ),
        migrations.AddField(
            model_name='person',
            name='diet_no_soy',
            field=models.BooleanField(default=False, verbose_name='No soy'),
        ),
        migrations.AddField(
            model_name='person',
            name='diet_no_tree_nuts',
            field=models.BooleanField(default=False, verbose_name='No tree nuts'),
        ),
        migrations.AddField(
            model_name='person',
            name='diet_other',
            field=models.TextField(blank=True, verbose_name='Other dietary restrictions'),
        ),
        migrations.AddField(
            model_name='person',
            name='diet_vegan',
            field=models.BooleanField(default=False, verbose_name='Vegan'),
        ),
        migrations.AddField(
            model_name='person',
            name='diet_vegetarian',
            field=models.BooleanField(default=False, verbose_name='Vegetarian'),
        ),
        # Data migration — copy old dietary_restrictions into diet_other
        migrations.RunPython(copy_dietary_data, migrations.RunPython.noop),
        # Remove the old field
        migrations.RemoveField(
            model_name='person',
            name='dietary_restrictions',
        ),
    ]
