# Generated by Django 6.0.1 on 2026-03-26 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkaRe', '0025_dietary_restructure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Arrived at'),
        ),
        migrations.AddField(
            model_name='person',
            name='attendance_status',
            field=models.CharField(choices=[('expected', 'Expected'), ('arrived', 'Arrived'), ('departed', 'Departed'), ('not_coming', 'Not coming')], default='expected', max_length=20, verbose_name='Attendance status'),
        ),
        migrations.AddField(
            model_name='person',
            name='departed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Departed at'),
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('expected', 'Expected'), ('arrived', 'Arrived'), ('departed', 'Departed'), ('not_coming', 'Not coming')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='SkaRe.person')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
