# Generated by Django 6.0.1 on 2026-03-26 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkaRe', '0026_attendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SailTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(choices=[('p550', 'P550'), ('sail', 'Sailboat'), ('other', 'Other boat'), ('spare', 'Spare')], max_length=10)),
                ('rfid_uid', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('ashore', 'Ashore'), ('on_water', 'On water'), ('lost', 'Lost')], default='ashore', max_length=20)),
                ('pending_pairing', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sail_tickets', to='SkaRe.boat')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SailTicketLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ashore', 'Ashore'), ('on_water', 'On water'), ('lost', 'Lost')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='SkaRe.sailticket')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
