# Generated by Django 6.0.1 on 2026-03-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkaRe', '0027_sail_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sailticket',
            name='rfid_uid',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
