# Generated by Django 6.0.1 on 2026-03-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkaRe', '0028_alter_sailticket_rfid_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='wants_small_hat',
            field=models.BooleanField(default=False, help_text='Whether the organizer wants a small hat (S/M)', verbose_name='Wants small hat (S/M)'),
        ),
    ]
