# Generated by Django 6.0.1 on 2026-03-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkaRe', '0030_boat_color_free_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='diet_no_fruits',
        ),
        migrations.RemoveField(
            model_name='person',
            name='diet_no_tree_nuts',
        ),
        migrations.AlterField(
            model_name='person',
            name='diet_lactose_free',
            field=models.BooleanField(default=False, verbose_name='Lactose-free'),
        ),
    ]
