# Generated by Django 6.0.1 on 2026-03-31 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkaRe', '0031_remove_diet_tree_nuts_fruits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Boat name'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='sail_color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='sail color'),
        ),
    ]
