# Generated by Django 6.0.1 on 2026-04-29 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkaRe', '0032_alter_boat_name_alter_boat_sail_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='category',
            field=models.CharField(choices=[('Q', 'Q – Žabičky a vlčata'), ('S', 'S – Skautky a skauti'), ('R', 'R – Rangers a roveři'), ('D', 'D – Dospělí'), ('SN', 'SN – Skautští námořníci'), ('DN', 'DN – Dospělí námořníci'), ('OZ', 'OŽ – Open Žáci'), ('OD', 'OD – Open Dospělí'), ('MS', 'MS – Modrá stuha'), ('ŠK', 'ŠK – Štít konstruktérů'), ('MSS', 'MSS – Modrá stužka')], max_length=3, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='eventsettings',
            name='editing_deadline',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 1, 21, 59, 59, tzinfo=datetime.timezone.utc), help_text='Deadline for editing Units and Participants'),
        ),
        migrations.AlterField(
            model_name='eventsettings',
            name='registration_deadline',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 1, 21, 59, 59, tzinfo=datetime.timezone.utc), help_text='Deadline for creating new Units and Participants'),
        ),
    ]
