from django.urls import path
from . import views

app_name = 'SkaRe'

urlpatterns = [
    path('', views.home, name='home'),
    path('lode/', views.boats_on_water, name='boats_on_water'),
    path('user/login/', views.user_login, name='login'),
    path('user/logout/', views.user_logout, name='logout'),
    path('user/register/', views.user_register, name='register'),
    path('user/forgot_password/', views.forgot_password, name='forgot_password'),
    path('unit/register/', views.register_unit, name='register_unit'),
    path('unit/list/', views.list_units, name='list_units'),
    path('unit/edit/<int:unit_id>/', views.edit_unit, name='edit_unit'),
    path('unit/editors/<int:unit_id>/', views.manage_unit_editors, name='manage_unit_editors'),
    path('individual/register/', views.register_individual_participant, name='register_individual_participant'),
    path('individual/list/', views.list_individual_participants, name='list_individual_participants'),
    path('individual/edit/<int:participant_id>/', views.edit_individual_participant, name='edit_individual_participant'),
    path('individual/editors/<int:participant_id>/', views.manage_individual_participant_editors, name='manage_individual_participant_editors'),
    path('organizer/register/', views.register_organizer, name='register_organizer'),
    path('organizer/list/', views.list_organizers, name='list_organizers'),
    path('organizer/edit/<int:organizer_id>/', views.edit_organizer, name='edit_organizer'),
    path('organizer/editors/<int:organizer_id>/', views.manage_organizer_editors, name='manage_organizer_editors'),
    path('organizer/exports/units-csv/', views.exports_organizer_units_csv, name='exports_organizer_units_csv'),
    path('all/list/', views.list_all, name='list_all'),
    path('merchandise/list/', views.list_merchandise, name='list_merchandise'),
    path('entities/manage/', views.manage_entities, name='manage_entities'),
    path('boats/', views.boat_list, name='boat_list'),
    path('boats/register/', views.boat_register, name='boat_register'),
    path('boats/api/sail-lookup/', views.boat_sail_lookup, name='boat_sail_lookup'),
    path('boats/api/my-unit/', views.boat_my_unit, name='boat_my_unit'),
    path('boats/<int:boat_id>/', views.boat_detail, name='boat_detail'),
    path('boats/<int:boat_id>/edit/', views.boat_edit, name='boat_edit'),
    path('boats/<int:boat_id>/delete/', views.boat_delete, name='boat_delete'),
    path('boats/<int:boat_id>/lend/', views.boat_lend, name='boat_lend'),
    path('persons/<int:person_id>/lend/', views.person_lend, name='person_lend'),
    path('crews/', views.crew_list, name='crew_list'),
    path('crews/register/', views.crew_register, name='crew_register'),
    path('crews/export/csv/', views.crew_export_csv, name='crew_export_csv'),
    path('crews/<int:crew_id>/', views.crew_detail, name='crew_detail'),
    path('crews/<int:crew_id>/edit/', views.crew_edit, name='crew_edit'),
    path('crews/<int:crew_id>/delete/', views.crew_delete, name='crew_delete'),
    path('crews/all/', views.crew_all, name='crew_all'),
    path('crews/all/export/csv/', views.crew_all_export_csv, name='crew_all_export_csv'),
    path('crews/all/<int:crew_id>/', views.crew_detail_staff, name='crew_detail_staff'),
    path('crews/all/<int:crew_id>/export/csv/', views.crew_export_single_csv, name='crew_export_single_csv'),
    # InfoDesk
    path('infodesk/', views.infodesk_dashboard, name='infodesk_dashboard'),
    path('infodesk/registrations/', views.infodesk_registrations, name='infodesk_registrations'),
    path('infodesk/registrations/<int:entity_id>/confirm/', views.infodesk_confirm_entity, name='infodesk_confirm_entity'),
    path('infodesk/registrations/<int:entity_id>/reject/', views.infodesk_reject_entity, name='infodesk_reject_entity'),
    path('infodesk/registrations/bulk-confirm/', views.infodesk_bulk_confirm, name='infodesk_bulk_confirm'),
    path('infodesk/tent-borrowers/', views.infodesk_tent_borrowers, name='infodesk_tent_borrowers'),
    # Attendance
    path('infodesk/attendance/units/', views.attendance_units_list, name='attendance_units_list'),
    path('infodesk/attendance/units/<int:unit_id>/', views.attendance_unit_detail, name='attendance_unit_detail'),
    path('infodesk/attendance/units/<int:unit_id>/mark-all-arrived/', views.attendance_unit_mark_all_arrived, name='attendance_unit_mark_all_arrived'),
    path('infodesk/attendance/individuals/', views.attendance_individuals_list, name='attendance_individuals_list'),
    path('infodesk/attendance/organizers/', views.attendance_organizers_list, name='attendance_organizers_list'),
    path('infodesk/attendance/persons/<int:person_id>/set-status/', views.attendance_set_status, name='attendance_set_status'),
    # Tickets
    path('infodesk/tickets/', views.ticket_list, name='ticket_list'),
    path('infodesk/tickets/lookup/', views.ticket_lookup, name='ticket_lookup'),
    path('infodesk/tickets/create-bulk/', views.ticket_create_bulk, name='ticket_create_bulk'),
    path('infodesk/tickets/on-water/', views.ticket_on_water, name='ticket_on_water'),
    path('infodesk/tickets/export/csv/', views.ticket_export_csv, name='ticket_export_csv'),
    path('infodesk/tickets/<int:ticket_id>/', views.ticket_detail, name='ticket_detail'),
    path('infodesk/tickets/<int:ticket_id>/set-status/', views.ticket_set_status, name='ticket_set_status'),
    path('infodesk/tickets/<int:ticket_id>/pair-rfid/', views.ticket_pair_rfid, name='ticket_pair_rfid'),
    path('infodesk/tickets/<int:ticket_id>/unpair-rfid/', views.ticket_unpair_rfid, name='ticket_unpair_rfid'),
    path('infodesk/tickets/<int:ticket_id>/cancel-pairing/', views.ticket_cancel_pairing, name='ticket_cancel_pairing'),
    path('infodesk/tickets/<int:ticket_id>/assign-boat/', views.ticket_assign_boat, name='ticket_assign_boat'),
    path('infodesk/tickets/<int:ticket_id>/unassign-boat/', views.ticket_unassign_boat, name='ticket_unassign_boat'),
    # RFID reader API
    path('api/rfid/alive/', views.rfid_alive, name='rfid_alive'),
    path('api/rfid/scan/', views.rfid_scan, name='rfid_scan'),
    # Exports
    path('infodesk/exports/', views.exports_index, name='exports_index'),
    path('infodesk/exports/kitchen/csv/', views.exports_kitchen_csv, name='exports_kitchen_csv'),
    path('infodesk/exports/kitchen/print/', views.exports_kitchen_print, name='exports_kitchen_print'),
    path('infodesk/exports/medical/csv/', views.exports_medical_csv, name='exports_medical_csv'),
    path('infodesk/exports/medical/print/', views.exports_medical_print, name='exports_medical_print'),
]

